const dataSlider = [
    {
        h1: "Discover the world's top designers & creatives.",
        h2: "Dribbble is the leading destination to find & showcase creative work and home to the world's best design professionals.",
        picture: "assets/img/slider.png",

    },
    {
        h1: "Discover the world's top designers & creatives.",
        h2: "Dribbble is the leading destination to find & showcase creative work and home to the world's best design professionals.",
        picture: "assets/img/slider.png",

    },
    {
        h1: "Discover the world's top designers & creatives.",
        h2: "Dribbble is the leading destination to find & showcase creative work and home to the world's best design professionals.",
        picture: "assets/img/slider.png",

    },
    {
        h1: "Discover the world's top designers & creatives.",
        h2: "Dribbble is the leading destination to find & showcase creative work and home to the world's best design professionals.",
        picture: "assets/img/slider.png",

    },
    {
        h1: "Discover the world's top designers & creatives.",
        h2: "Dribbble is the leading destination to find & showcase creative work and home to the world's best design professionals.",
        picture: "assets/img/slider.png",

    },

]

const data = [
    {

        index: 0,
        title: "Antonia Font",
        liked: false,
        picture: "assets/img/ejemplo.jpeg",
        author: "assets/img/logo.png",
        likes: 2,
        views: 13,
        categories: ["cat_04", "cat_05", "cat_07", "cat_08"],
    },
    { 
        index: 1,
        title: "Antonia Font",
        liked: true,
        picture: "assets/img/ejemplo.jpeg",
        author: "assets/img/logo.png",
        likes: 2,
        views: 13,
        categories: ["cat_05", "cat_02", "cat_03", "cat_04", "cat_06", "cat_07"],
    },
    {  
        index: 2,
        title: "Antonia Font",
        liked: false,
        picture: "assets/img/ejemplo.jpeg",
        author: "assets/img/logo.png",
        likes: 2,
        views: 13,
        categories: ["cat_04", "cat_05", "cat_07", "cat_08"],
    },
    {
        index: 3,
        title:
        "Antonia Font",
        liked: true,
        picture: "assets/img/ejemplo.jpeg",
        author: "assets/img/logo.png",
        likes: 2,
        views: 13,
        categories: ["cat_05", "cat_02", "cat_03", "cat_04", "cat_06", "cat_07"],
    },
        {
        index: 4,
        title: "Antonia Font",
        liked: false,
        picture: "assets/img/ejemplo.jpeg",
        author: "assets/img/logo.png",
        likes: 2,
        views: 13,
        categories: ["cat_09", "cat_04", "cat_05", "cat_07", "cat_08"],
    },
    { 
        index: 5,
        title: "Antonia Font",
        liked: true,
        picture: "assets/img/ejemplo.jpeg",
        author: "assets/img/logo.png",
        likes: 2,
        views: 13,
        categories: ["cat_04", "cat_05", "cat_07", "cat_08"],
    },
    {   
        index: 6,
        title: "Antonia Font",
        liked: false,
        picture: "assets/img/ejemplo.jpeg",
        author: "assets/img/logo.png",
        likes: 2,
        views: 13,
        categories: ["cat_07", "cat_04", "cat_05", "cat_08"],
    },
    {    
        index: 7,
        title: "Antonia Font",
        liked: true,
        picture: "assets/img/ejemplo.jpeg",
        author: "assets/img/logo.png",
        likes: 2,
        views: 13,
        categories: ["cat_09", "cat_03", "cat_04", "cat_06", "cat_07"],
    },
    {    
        index: 8,
        title: "Antonia Font",
        liked: false,
        picture: "assets/img/ejemplo.jpeg",
        author: "assets/img/logo.png",
        likes: 2,
        views: 13,
        categories: ["cat_01", "cat_04", "cat_05", "cat_07", "cat_08"],
    },
    {     
        index: 9,
        title: "Antonia Font",
        liked: true,
        picture: "assets/img/ejemplo.jpeg",
        author: "assets/img/logo.png",
        likes: 2,
        views: 13,
        categories: ["cat_02", "cat_03", "cat_04", "cat_06", "cat_07"],
    },
        {     
        index: 10,
        title: "Antonia Font",
        liked: false,
        picture: "assets/img/ejemplo.jpeg",
        author: "assets/img/logo.png",
        likes: 2,
        views: 13,
        categories: ["cat_07", "cat_04", "cat_05", "cat_08"],
    },
    {   
        index: 11,
        title: "Antonia Font",
        liked: true,
        picture: "assets/img/ejemplo.jpeg",
        author: "assets/img/logo.png",
        likes: 2,
        views: 13,
        categories: ["cat_04", "cat_05", "cat_07", "cat_08"],
    },
    { 
        index: 12,
        title: "Antonia Font",
        liked: false,
        picture: "assets/img/ejemplo.jpeg",
        author: "assets/img/logo.png",
        likes: 2,
        views: 13,
        categories: ["cat_07", "cat_04", "cat_05", "cat_08"],
    },
    { 
        index: 13,
        title: "Antonia Font",
        liked: true,
        picture: "assets/img/ejemplo.jpeg",
        author: "assets/img/logo.png",
        likes: 2,
        views: 13,
        categories: [ "cat_06", "cat_02", "cat_03", "cat_04", "cat_07"],
    },
    {
  
        index: 14,
        title: "Antonia Font",
        liked: false,
        picture: "assets/img/ejemplo.jpeg",
        author: "assets/img/logo.png",
        likes: 2,
        views: 13,
        categories: ["cat_07", "cat_04", "cat_05", "cat_08"],
    },
    {    
        index: 15,
        title: "Antonia Font",
        liked: true,
        picture: "assets/img/ejemplo.jpeg",
        author: "assets/img/logo.png",
        likes: 2,
        views: 13,
        categories: [ "cat_04", "cat_02", "cat_03", "cat_06", "cat_07"],
    },
        {     
        index: 16,
        title: "Antonia Font",
        liked: false,
        picture: "assets/img/ejemplo.jpeg",
        author: "assets/img/logo.png",
        likes: 2,
        views: 13,
        categories: ["cat_04", "cat_05", "cat_07", "cat_08"],
    },
    {
        index: 17,
        title: "Antonia Font",
        liked: true,
        picture: "assets/img/ejemplo.jpeg",
        author: "assets/img/logo.png",
        likes: 2,
        views: 13,
        categories: ["cat_02", "cat_03", "cat_04", "cat_06", "cat_07"],
    },
    {  
        index: 18,
        title: "Antonia Font",
        liked: false,
        picture: "assets/img/ejemplo.jpeg",
        author: "assets/img/logo.png",
        likes: 2,
        views: 13,
        categories: ["cat_04", "cat_05", "cat_07", "cat_08"],
    },
    {   
        index: 19,
        title: "Antonia Font",
        liked: true,
        picture: "assets/img/ejemplo.jpeg",
        author: "assets/img/logo.png",
        likes: 2,
        views: 13,
        categories: ["cat_07", "cat_04", "cat_05", "cat_08"],
    },
    {
            index: 20,
        title: "Antonia Font",
        liked: false,
        picture: "assets/img/ejemplo.jpeg",
        author: "assets/img/logo.png",
        likes: 2,
        views: 113,
        categories: ["cat_04", "cat_05", "cat_07", "cat_08"],
    },
    {    
        index: 21,
        title: "Antonia Font",
        liked: true,
        picture: "assets/img/ejemplo.jpeg",
        author: "assets/img/logo.png",
        likes: 2,
        views: 13,
        categories: ["cat_02", "cat_03", "cat_04", "cat_06", "cat_07"],
    },
        {   
        index: 22,
        title: "Antonia Font",
        liked: false,
        picture: "assets/img/ejemplo.jpeg",
        author: "assets/img/logo.png",
        likes: 2,
        views: 13,
        categories: ["cat_04", "cat_05", "cat_07", "cat_08"],
    },
    {     
        index: 23,
        title: "Antonia Font",
        liked: true,
        picture: "assets/img/ejemplo.jpeg",
        author: "assets/img/logo.png",
        likes: 2,
        views: 13,
        categories: ["cat_02", "cat_03", "cat_04", "cat_06", "cat_07"],
    },
    {      
        index: 24,
        title: "Antonia Font",
        liked: true,
        picture: "assets/img/ejemplo.jpeg",
        author: "assets/img/logo.png",
        likes: 2,
        views: 13,
        categories: ["cat_07", "cat_04", "cat_05", "cat_08"],
    },
    {     
        index: 25,
        title: "Antonia Font",
        liked: false,
        picture: "assets/img/ejemplo.jpeg",
        author: "assets/img/logo.png",
        likes: 2,
        views: 13,
        categories: ["cat_04", "cat_05", "cat_07", "cat_08"],
    },
    {   
        index: 26,
        title: "Antonia Font",
        liked: true,
        picture: "assets/img/ejemplo.jpeg",
        author: "assets/img/logo.png",
        likes: 2,
        views: 13,
        categories: ["cat_02", "cat_03", "cat_04", "cat_06", "cat_07"],
    },
    {    
        index: 27,
        title: "Antonia Font",
        liked: false,
        picture: "assets/img/ejemplo.jpeg",
        author: "assets/img/logo.png",
        likes: 2,
        views: 13,
        categories: ["cat_02", "cat_03", "cat_04", "cat_06", "cat_07"],
    },
    {     
        index: 28,
        title: "Antonia Font",
        liked: true,
        picture: "assets/img/ejemplo.jpeg",
        author: "assets/img/logo.png",
        likes: 2,
        views: 13,
        categories: ["cat_02", "cat_03", "cat_04", "cat_06", "cat_07"],
    },
        {    
        index: 29,
        title: "Antonia Font",
        liked: false,
        picture: "assets/img/ejemplo.jpeg",
        author: "assets/img/logo.png",
        likes: 2,
        views: 13,
        categories: ["cat_02", "cat_03", "cat_04", "cat_06", "cat_07"],
    },
]
